version: '3.5'

services:
  api:
    container_name: 'snippet-permission-app'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      DB_HOST: permission-db
      DB_PORT: ${DB_PORT}
    networks:
      - snippet_network
      - permission_network

  db:
    container_name: 'permission-db'
    image: postgres:alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    networks:
      - permission_network

    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata:

networks:
  permission_network:
    driver: bridge
  snippet_network:
    external: true